[project]
name = "communitybot"
version = "0.1.0"
description = "Community Discord Bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "anthropic>=0.40.0",
    "databases>=0.9.0",
    "dotenv>=0.9.9",
    "py-cord>=2.6.1",
    "sqlalchemy>=2.0.44",
]
